# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: antipop.fm
email: ketarok@gmail.com
description: 面白くてためになるポッドキャスト
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antipop.fm" # the base hostname & protocol for your site
twitter_username: kentaro
github_username:  kentaro
permalink: /:title/

# Build settings
markdown: kramdown
